### PR TITLE
adding support to check when the module/service is ready

### PR DESCRIPTION
**Pull request by nitrag**
Instead of guessing when the module/service is ready, we can check this way and get the listeners setup ASAP.

~~~
var handle;
handle = setInterval(function(){
	if(!TiBeacons.isReady())
		return;
	
	Ti.API.info("Okay! Module is ready!");	
	clearInterval(handle);
	handle = null;
	
	//setup your event listeners here
}, 1000);

~~~

### CODE REVIEW

**Comment by RBAtkins0n** [comment]
Noob question, is there a built version of the module with this functionality in existence?

**Comment by nitrag** [comment]
Yes, on my fork.

https://github.com/nitrag/liferay-android-beacons/blob/9e7da951c100a2f28f044ba663d1b6651cd517d5/dist/com.liferay.beacons-android-0.4.zip

**Comment by RBAtkins0n** [comment]
Awesome, thanks for the great work!

**Comment by jamesfalkner** [comment]
Thanks for the contribution!

**Pull request merged**
